# Site settings
title: Innovative Design Engineering
email: info@ide-nc.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ide-nc.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
